name: VillageDefenseMythicMobs
version: ${project.version}
main: me.hsgamer.villagedefensemythicmobs.VillageDefenseMythicMobs
api-version: 1.13
depend: [ VillageDefense ]
softdepend:
  - MythicMobs
authors: [ HSGamer ]
